# Generated by Django 5.0.4 on 2024-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='username',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
