# Generated by Django 5.0.4 on 2024-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermanage_email_alter_usermanage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
