# Generated by Django 5.0.4 on 2024-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermanage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
