# Generated by Django 5.0.4 on 2024-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermanage_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='address_index',
            field=models.IntegerField(default='0', unique=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='iin',
            field=models.IntegerField(default='0', unique=True, verbose_name='ИИН'),
        ),
    ]
