# Generated by Django 5.0.4 on 2024-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermanage_address_index_usermanage_iin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='role',
        ),
    ]
