# Generated by Django 5.0.4 on 2024-05-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usermanage_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
