# Generated by Django 5.0.4 on 2024-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermanage_address_index_alter_usermanage_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='address_index',
            field=models.IntegerField(default=0, unique=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='iin',
            field=models.IntegerField(default=0, unique=True, verbose_name='ИИН'),
        ),
    ]
