# Generated by Django 5.0.4 on 2024-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usermanage_address_index_alter_usermanage_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='iin',
            field=models.CharField(default=0, unique=True, verbose_name='ИИН'),
        ),
    ]
