# Generated by Django 5.0.4 on 2024-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usermanage_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='address_index',
            field=models.CharField(unique=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='iin',
            field=models.CharField(unique=True, verbose_name='ИИН'),
        ),
    ]
