# Generated by Django 5.0.4 on 2024-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('continuing', 'Continuing')], default='pending', max_length=20),
        ),
    ]
