# Generated by Django 5.0.4 on 2024-05-02 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 8, 16, 6, 533313, tzinfo=datetime.timezone.utc)),
        ),
    ]
