# Generated by Django 5.0.4 on 2024-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cycle',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='step',
            field=models.CharField(default='охрана', max_length=20),
        ),
        migrations.AlterField(
            model_name='pay',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='Прикрепите ваш чек'),
        ),
    ]
