# Generated by Django 5.0.4 on 2024-05-05 09:35

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_cycle_order_step_alter_pay_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='file',
            field=models.FileField(upload_to='', validators=[app.validators.validate_file_extension], verbose_name='Прикрепите ваш чек'),
        ),
    ]
