# Generated by Django 5.0.4 on 2024-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_manufactory_alter_order_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight_left',
            field=models.IntegerField(default=0),
        ),
    ]
