# Generated by Django 5.0.4 on 2024-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_weight_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manufactory',
            field=models.CharField(choices=[('4 цех', '4 цех'), ('ЦПШ', 'ЦПШ')], default='Не указано', max_length=20),
        ),
    ]
