# Generated by Django 5.0.4 on 2024-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_manufactory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.CharField(choices=[('юр.лицо', 'юр.лицо'), ('физ.лицо', 'физ.лицо')], default='физ.лицо', max_length=20),
        ),
    ]
