# Generated by Django 5.0.4 on 2024-05-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-40', '20-40'), ('5-40', '5-40'), ('40-70', '40-70'), ('Бутовый камень', 'Бутовый камень')], max_length=100, verbose_name='Фракция щебня')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fraction_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fractionprice'),
        ),
    ]
