# Generated by Django 5.0.4 on 2024-05-11 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_fractionprice_order_fraction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, т'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mass',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Масса щебня (тонн)'),
        ),
    ]
