# Generated by Django 5.0.4 on 2024-05-20 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_cycle_total_order_cycles_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_reserved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
