# Generated by Django 5.0.4 on 2024-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionprice',
            name='fraction',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-40', '20-40'), ('5-40', '5-40'), ('40-70', '40-70'), ('Rubble stone', 'Бутовый камень')], max_length=100),
        ),
    ]
